### ISSUE TITLE
NoMethodError: undefined method rvm_environment for #<Chef::Provider::Package::RVMRubygems:0x00000000ece280>

### ISSUE THREAD

**Issue by akshah123** [martinisoft/chef-rvm#283] opened 2014-12-08 19:09 UTC
I am getting this error with chef-client 12.0.0.  

Existing setup was working just fine.  Until we tried a new vagrant setup that bootstrapped with the latest chef-client 12.0.0. That errored out with NoMethodError: undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000000ece280>.

After I forced the vagrant process to version 11.16.4-1, it again worked without this error.

I didn't see anything that would suggest this problem in the release notes for this version but perhaps I missed something. 

Any help is greatly appreciated.

Here is the entire error output:

```
==> default: [2014-12-08T16:47:12+00:00] WARN: Current  rvm_gem[bundler]: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:48:in `gem_package_wrapper'
==> default: 
==> default: ================================================================================
==> default: Error executing action `install` on resource 'rvm_gem[bundler]'
==> default: ================================================================================
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000000ece280>
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:129:in `block in install_package'
==> default: 
==> default: /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:127:in `each'
==> default: /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:127:in `install_package'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:35:in `block (3 levels) in class_from_file'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:34:in `each'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:34:in `block (2 levels) in class_from_file'
==> default: 
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /var/chef/cache/cookbooks/rvm/providers/global_gem.rb
==> default: 
==> default:  48:   g = rvm_gem new_resource.package_name do
==> default: 
==> default:  49:     ruby_string ruby_global_gemset
==> default: 
==> default:  50:     source      new_resource.source if new_resource.source
==> default:  51:     options     new_resource.options if new_resource.options
==> default:  52:     version     new_resource.version if new_resource.version
==> default:  53:     gem_binary  new_resource.gem_binary if new_resource.gem_binary
==> default:  54:     user        new_resource.user
==> default:  55:     action      :nothing
==> default: 
==> default:  56:   end
==> default: 
==> default:  57:   g.run_action(exec_action)
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:48:in `gem_package_wrapper'
==> default: 
==> default: 
==> default: rvm_gem("bundler") do
==> default:   provider Chef::Provider::Package::RVMRubygems
==> default:   action [:nothing]
==> default:   retries 0
==> default:   retry_delay 2
==> default: 
==> default:   default_guard_interpreter :default
==> default:   cookbook_name "rvm"
==> default:   ruby_string "ruby-2.1.1@global"
==> default:   user "vagrant"
==> default:   version "1.6.2"
==> default:   gem_binary "gem"
==> default: 
==> default:   package_name "bundler"
==> default: end
==> default: 
==> default: 
==> default: 
==> default: 
==> default: ================================================================================
==> default: Error executing action `install` on resource 'rvm_global_gem[bundler]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: rvm_gem[bundler] (/var/chef/cache/cookbooks/rvm/providers/global_gem.rb line 48) had an error: NoMethodError: undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000000ece280>
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:129:in `block in install_package'
==> default: /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:127:in `each'
==> default: /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:127:in `install_package'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
==> default: 
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:35:in `block (3 levels) in class_from_file'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:34:in `each'
==> default: /var/chef/cache/cookbooks/rvm/providers/global_gem.rb:34:in `block (2 levels) in class_from_file'
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb
==> default: 
==> default: 191:           rvm_global_gem gem[:name] do
==> default: 192:             user      opts[:user]
==> default: 
==> default: 193:             [:version, :action, :options, :source].each do |attr|
==> default: 194:               send(attr, gem[attr]) if gem[attr]
==> default: 195:             end
==> default: 196:           end
==> default: 197:         end
==> default: 
==> default: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:191:in `block in install_rubies'
==> default: 
==> default: 
==> default: rvm_global_gem("bundler") do
==> default:   action :install
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default: 
==> default:   cookbook_name "rvm"
==> default:   recipe_name "user"
==> default:   user "vagrant"
==> default:   package_name "bundler"
==> default: end
==> default: 
==> default: 
==> default: 
==> default: [2014-12-08T16:47:14+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2014-12-08T16:47:14+00:00] ERROR: Running exception handlers
==> default: [2014-12-08T16:47:14+00:00] ERROR: Exception handlers complete
==> default: [2014-12-08T16:47:14+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2014-12-08T16:47:14+00:00] INFO: Sending resource update report (run-id: 02293aaf-dd56-4eb5-9da8-1052881199f8)
==> default: [2014-12-08T16:47:14+00:00] ERROR: rvm_global_gem[bundler] (rvm::user line 191) had an error: NoMethodError: rvm_gem[bundler] (/var/chef/cache/cookbooks/rvm/providers/global_gem.rb line 48) had an error: NoMethodError: undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000000ece280>
==> default: [2014-12-08T16:47:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by akshah123** [comment] 2015-01-06 16:57
@martinisoft, @nomadium  has confirmed that it will not break Chef 11 support in the PR.

It would be great to have the PR merged.

**Comment by martinisoft** [comment] 2015-01-06 17:01
@akshah123 I'll look at merging the change today.

**Comment by mmahalwy** [comment] 2015-01-11 05:00
is this merged yet?

**Comment by nomadium** [comment] 2015-01-12 13:43
@mmahalwy Yes, it was merged recently.

**Comment by david-crowder** [comment] 2015-03-19 17:15
Just ran into this issue and I was curious if there was any plan to cut a release with the fix? Obviously I am late to the chef 12 party, but it would be awesome to consume a tagged version of the cookbook :smiley:

**Comment by noahgibbs** [comment] 2015-03-31 22:37
And is there a Chef 12 fix yet, or just Chef 11?

**Comment by vladimir-low** [comment] 2015-04-15 18:39
@martinisoft, as soon as master has some more issues, are you planning to release the patch for this issue to Chef Supermarket?

**Comment by tim-saki** [comment] 2015-04-28 01:56
Is there a plan to release it on supermarket?

**Comment by Ditchou** [comment] 2015-05-01 10:01
up, I need this fix!

**Comment by nand0p** [comment] 2015-05-03 01:13
what is best practice until the issue is fixed?

**Comment by okram999** [comment] 2015-05-05 05:32
i am getting a below error, but sure if i am also being hit by the same bug. The version is Chef: 12.3.0



   - update content in file /etc/rvmrc from b7a449 to 57f6fe
    --- /etc/rvmrc	2015-05-04 21:59:37.369581808 -0700
    +++ /tmp/chef-rendered-template20150504-31986-zrq8o0	2015-05-04 22:23:31.064638259 -0700
    @@ -6,5 +6,4 @@
     export rvm_path="/opt/mount1/rvm"
     
     export rvm_gem_options="--no-rdoc --no-ri"
    -umask u=rwx,g=rwx,o=rx
    - change mode from '0664' to '0644'
  * execute[install system-wide RVM] action run (skipped due to not_if)
  * execute[upgrade system-wide RVM to none] action run (skipped due to not_if)
Recipe: rvm::system
  * rvm_ruby[ruby-2.1.1] action install/home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_chef_user_environment.rb:32: warning: class variable access from toplevel
 (up to date)
  * rvm_default_ruby[system] action create/home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_chef_user_environment.rb:32: warning: class variable access from toplevel
 (up to date)
  * rvm_global_gem[bundler] action install/home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_chef_user_environment.rb:32: warning: class variable access from toplevel

    * execute[Add bundler to /opt/mount1/rvm/gemsets/global.gems] action run (skipped due to not_if)
[2015-05-04T22:23:32-07:00] WARN: Cloning resource attributes for rvm_gem[bundler] from prior resource (CHEF-3694)
[2015-05-04T22:23:32-07:00] WARN: Previous rvm_gem[bundler]: /home/ec2-user/chef-solo/cookbooks-2/123hp_jenkins/recipes/rubies.rb:4:in `from_file'
[2015-05-04T22:23:32-07:00] WARN: Current  rvm_gem[bundler]: /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:48:in `gem_package_wrapper'
    * rvm_gem[bundler] action install
      
      ================================================================================
      Error executing action `install` on resource 'rvm_gem[bundler]'
      ================================================================================
      
      NoMethodError
      -------------
      undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000008d52610>
      
      Cookbook Trace:
      ---------------
      /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_rubygems_package.rb:129:in `block in install_package'
      /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_rubygems_package.rb:127:in `each'
      /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_rubygems_package.rb:127:in `install_package'
      /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
      /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:35:in `block (3 levels) in class_from_file'
      /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:34:in `each'
      /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:34:in `block (2 levels) in class_from_file'
      
      Resource Declaration:
      ---------------------
      # In /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb
      
       48:   g = rvm_gem new_resource.package_name do
       49:     ruby_string ruby_global_gemset
       50:     source      new_resource.source if new_resource.source
       51:     options     new_resource.options if new_resource.options
       52:     version     new_resource.version if new_resource.version
       53:     gem_binary  new_resource.gem_binary if new_resource.gem_binary
       54:     user        new_resource.user
       55:     action      :nothing
       56:   end
       57:   g.run_action(exec_action)
      
      Compiled Resource:
      ------------------
      # Declared in /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:48:in `gem_package_wrapper'
      
      rvm_gem("bundler") do
        provider Chef::Provider::Package::RVMRubygems
        action [:nothing]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :rvm_gem
        cookbook_name :rvm
        ruby_string "ruby-2.1.1@global"
        gem_binary "gem"
        package_name "bundler"
        version "1.9.6"
      end
      
    
    ================================================================================
    Error executing action `install` on resource 'rvm_global_gem[bundler]'
    ================================================================================
    
    NoMethodError
    -------------
    rvm_gem[bundler] (/home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb line 48) had an error: NoMethodError: undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000008d52610>
    
    Cookbook Trace:
    ---------------
    /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_rubygems_package.rb:129:in `block in install_package'
    /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_rubygems_package.rb:127:in `each'
    /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/rvm_rubygems_package.rb:127:in `install_package'
    /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:57:in `gem_package_wrapper'
    /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:35:in `block (3 levels) in class_from_file'
    /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:34:in `each'
    /home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb:34:in `block (2 levels) in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_recipe_helpers.rb
    
    191:           rvm_global_gem gem[:name] do
    192:             user      opts[:user]
    193:             [:version, :action, :options, :source].each do |attr|
    194:               send(attr, gem[attr]) if gem[attr]
    195:             end
    196:           end
    197:         end
    
    Compiled Resource:
    ------------------
    # Declared in /home/ec2-user/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_recipe_helpers.rb:191:in `block in install_rubies'
    
    rvm_global_gem("bundler") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :rvm_global_gem
      cookbook_name :rvm
      recipe_name "system"
      package_name "bundler"
    end
    

Running handlers:
[2015-05-04T22:23:34-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-04T22:23:34-07:00] ERROR: Exception handlers complete
[2015-05-04T22:23:34-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 2 resources updated in 16.244196065 seconds
[2015-05-04T22:23:34-07:00] ERROR: rvm_global_gem[bundler] (rvm::system line 191) had an error: NoMethodError: rvm_gem[bundler] (/home/ec2-user/chef-solo/cookbooks-2/rvm/providers/global_gem.rb line 48) had an error: NoMethodError: undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x00000008d52610>
[2015-05-04T22:23:34-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
~/workspace/123hp_utils [2.1.1@123_jenkins master*] 


i am using the knife solo to bootstrap a node and this recipe is also a part of the run-list. How do i apply the workaround? i made the changes in the file as in this https://github.com/martinisoft/chef-rvm/pull/284/files  but whenever i do a `knife solo cook user@servername'  the cookbook apears to be re-downloaded and hence the changes are all gone

**Comment by okram999** [comment] 2015-05-05 05:59
So, i rolled back the chef-client version to 11.16.4. And i don't have this issue.

**Comment by noahgibbs** [comment] 2015-05-05 14:29
Yup, that absolutely sounds like the same issue.

**Comment by trinitronx** [comment] 2015-05-07 01:09
interestingly enough... I'm running into this same error with `chef-client` version: `11.6.0` and rvm cookbook version `0.9.2`.

Error is similar

**Comment by trinitronx** [comment] 2015-05-08 02:48
Confirmed that running same version of this cookbook (`0.9.2`) under Chef `11.16.4` does not give the error.  Running under `12.3.0` gives the same error.  Seems like a bug regression in Chef.

**Comment by jklein** [comment] 2015-05-14 18:09
I got this same issue with the following versions:

```
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0
```

Is there a workaround or a fix?

**Comment by RichardWigley** [comment] 2015-05-18 14:58
Work around for knife solo users

* overwrite the chef-client with an earlier version 

During the bootstrap operation the chef-client is uploaded to the target system, typically the latest version currently 12.3 ish - rolling-back the client to an earlier version is one workaround:

Setting Chef-Client Bootstrap Version
````
knife solo bootstrap <ip-address | FQDN> --bootstrap-version 11.16.4
````
Example
````
knife solo bootstrap 10.0.0.1 --bootstrap-version 11.16.4
````

Maybe the same for knife bootstrap? But completely untested.

Rich

**Comment by trinitronx** [comment] 2015-05-21 22:45
This bug has been fixed and merged in #284.  If you are comfortable with using `Berkshelf`, [you can use the latest on the `master` branch from github, or lock to a specific commit id using `ref`][1].  Otherwise, the workaround mentioned by @RichardWigley by using an old version of Chef will allow you to keep using the old version of this cookbook until the new release makes it to [Chef Supermarket][2].

[1]: https://github.com/martinisoft/chef-rvm/pull/284#issuecomment-104431793
[2]: https://supermarket.chef.io

**Comment by shubhamitc** [comment] 2015-07-22 16:29
I have tried it with latest chef-12.4.0 and berks to download the latest check however issue seems to persist. 


    ================================================================================
    Error executing action `install` on resource 'rvm_gem[bundle]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `rvm_environment' for #<Chef::Provider::Package::RVMRubygems:0x000000089200b0>
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:129:in `block in install_package'
    /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:127:in `each'
    /var/chef/cache/cookbooks/rvm/libraries/rvm_rubygems_package.rb:127:in `install_package'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rails_dep/recipes/default.rb
    
     99:   rvm_gem "bundle" do
    100:     ruby_string "ruby-2.1.5@ruby_zicos"
    101:     action      :install
    102:   end
    103: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rails_dep/recipes/default.rb:99:in `from_file'
    
    rvm_gem("bundle") do
      provider Chef::Provider::Package::RVMRubygems
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :rvm_gem
      cookbook_name "rails_dep"
      recipe_name "default"
      ruby_string "ruby-2.1.5@ruby_zicos"
      gem_binary "gem"
      package_name "bundle"
      version "0.0.1"
    end
    
=============================================================================

It would be great if there is any fix. Or command to fetch the correct version of cookbook using berks.

**Comment by tchdp** [comment] 2015-07-24 20:45
I upgraded to the latest release of 0.9.4 and stopped having the problem. I pinned the version in my cookbook's metadata.rb

**Comment by martinisoft** [comment] 2015-08-19 22:02
Going to close this issue as the 0.9.4 release included a back-ported Chef 12 patch to resolve the issue.

**Closed by martinisoft** 2015-08-19 22:02 UTC
Labels: Bug, PR Submitted
